package com.run2gether.backend.model;
// Generated 07-may-2016 22:23:29 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activities", catalog = "run2gether_dev")
public class Activity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private User user;
	private String rute;
	private String timeKm;
	private Double km;
	private String duration;

	public Activity() {
	}

	public Activity(User user) {
		this.user = user;
	}

	public Activity(User user, String rute, String timeKm, Double km, String duration) {
		this.user = user;
		this.rute = rute;
		this.timeKm = timeKm;
		this.km = km;
		this.duration = duration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getUsers() {
		return this.user;
	}

	public void setUsers(User user) {
		this.user = user;
	}

	@Column(name = "rute")
	public String getRute() {
		return this.rute;
	}

	public void setRute(String rute) {
		this.rute = rute;
	}

	@Column(name = "timeKM")
	public String getTimeKm() {
		return this.timeKm;
	}

	public void setTimeKm(String timeKm) {
		this.timeKm = timeKm;
	}

	@Column(name = "km", precision = 22, scale = 0)
	public Double getKm() {
		return this.km;
	}

	public void setKm(Double km) {
		this.km = km;
	}

	@Column(name = "duration", length = 45)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

}
