package com.run2gether.backend.model;
// Generated 16-may-2016 18:34:41 by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Activities generated by hbm2java
 */
@Entity
@Table(name = "activities", catalog = "run2gether_dev")
public class Activities implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Users users;
	private String route;
	private String timeKm;
	private Double m;
	private String duration;
	private Integer idGroupActivities;

	public Activities() {
	}

	public Activities(Users users) {
		this.users = users;
	}

	public Activities(Users users, String route, String timeKm, Double m, String duration, Integer idGroupActivities) {
		this.users = users;
		this.route = route;
		this.timeKm = timeKm;
		this.m = m;
		this.duration = duration;
		this.idGroupActivities = idGroupActivities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "route")
	public String getRoute() {
		return route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@Column(name = "timeKM")
	public String getTimeKm() {
		return timeKm;
	}

	public void setTimeKm(String timeKm) {
		this.timeKm = timeKm;
	}

	@Column(name = "m", precision = 22, scale = 0)
	public Double getM() {
		return m;
	}

	public void setM(Double m) {
		this.m = m;
	}

	@Column(name = "duration", length = 45)
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "idGroupActivities")
	public Integer getIdGroupActivities() {
		return idGroupActivities;
	}

	public void setIdGroupActivities(Integer idGroupActivities) {
		this.idGroupActivities = idGroupActivities;
	}

}
