package com.run2gether.backend.model;
// Generated 24-may-2016 23:17:21 by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", catalog = "run2gether_dev")
public class Activity implements java.io.Serializable {

	private static final long serialVersionUID = 2L;
	private Integer id;
	private User user;
	private String route;
	private String timeKm;
	private Double m;
	private String duration;
	private Integer idGroupactivities;
	private Date dateModified;
	private Set<Checkpoint> checkpoints = new HashSet<Checkpoint>(0);

	public Activity() {
	}

	public Activity(User user) {
		this.user = user;
	}

	public Activity(User user, String route, String timeKm, Double m, String duration, Integer idGroupactivities,
			Date dateModified, Set<Checkpoint> checkpoints) {
		this.user = user;
		this.route = route;
		this.timeKm = timeKm;
		this.m = m;
		this.duration = duration;
		this.idGroupactivities = idGroupactivities;
		this.dateModified = dateModified;
		this.checkpoints = checkpoints;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "route")
	public String getRoute() {
		return route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@Column(name = "time_km")
	public String getTimeKm() {
		return timeKm;
	}

	public void setTimeKm(String timeKm) {
		this.timeKm = timeKm;
	}

	@Column(name = "m", precision = 22, scale = 0)
	public Double getM() {
		return m;
	}

	public void setM(Double m) {
		this.m = m;
	}

	@Column(name = "duration", length = 45)
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "id_groupactivities")
	public Integer getIdGroupactivities() {
		return idGroupactivities;
	}

	public void setIdGroupactivities(Integer idGroupactivities) {
		this.idGroupactivities = idGroupactivities;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", length = 19)
	public Date getDateModified() {
		return dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "activity")
	public Set<Checkpoint> getCheckpoints() {
		return checkpoints;
	}

	public void setCheckpoints(Set<Checkpoint> checkpoints) {
		this.checkpoints = checkpoints;
	}

	public void update(Activity modyAtt) {
		// user = modyAtt.user == null ? user : modyAtt.user;
		route = modyAtt.route == null ? route : modyAtt.route;
		timeKm = modyAtt.timeKm == null ? timeKm : modyAtt.timeKm;
		m = modyAtt.m == null ? m : modyAtt.m;
		duration = modyAtt.duration == null ? duration : modyAtt.duration;

		/**
		 * idGroupactivities: Una vez asignado un Grupo de Actividad a una
		 * activdad no se peude modificar
		 */
	}

}
