package com.run2gether.backend.model;
// Generated 16-may-2016 18:34:41 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Checkpoint generated by hbm2java
 */
@Entity
@Table(name = "checkpoint", catalog = "run2gether_dev")
public class Checkpoint implements java.io.Serializable {

	private static final long serialVersionUID = 2L;
	private CheckpointId id;
	private Double time;
	private Double lat;
	private Double lon;
	private Double alt;

	public Checkpoint() {
	}

	public Checkpoint(CheckpointId id) {
		this.id = id;
	}

	public Checkpoint(CheckpointId id, Double time, Double lat, Double lon, Double alt) {
		this.id = id;
		this.time = time;
		this.lat = lat;
		this.lon = lon;
		this.alt = alt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idActivitie", column = @Column(name = "idActivitie", nullable = false)),
			@AttributeOverride(name = "meter", column = @Column(name = "meter", nullable = false, precision = 22, scale = 0)) })
	public CheckpointId getId() {
		return id;
	}

	public void setId(CheckpointId id) {
		this.id = id;
	}

	@Column(name = "time", precision = 22, scale = 0)
	public Double getTime() {
		return time;
	}

	public void setTime(Double time) {
		this.time = time;
	}

	@Column(name = "lat", precision = 22, scale = 0)
	public Double getLat() {
		return lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	@Column(name = "lon", precision = 22, scale = 0)
	public Double getLon() {
		return lon;
	}

	public void setLon(Double lon) {
		this.lon = lon;
	}

	@Column(name = "Alt", precision = 22, scale = 0)
	public Double getAlt() {
		return alt;
	}

	public void setAlt(Double alt) {
		this.alt = alt;
	}

}
