package com.run2gether.backend.model;
// Generated 16-may-2016 18:34:41 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CheckpointId generated by hbm2java
 */
@Embeddable
public class CheckpointId implements java.io.Serializable {

	private static final long serialVersionUID = 3L;
	private int idActivitie;
	private double meter;

	public CheckpointId() {
	}

	public CheckpointId(int idActivitie, double meter) {
		this.idActivitie = idActivitie;
		this.meter = meter;
	}

	@Column(name = "idActivitie", nullable = false)
	public int getIdActivitie() {
		return idActivitie;
	}

	public void setIdActivitie(int idActivitie) {
		this.idActivitie = idActivitie;
	}

	@Column(name = "meter", nullable = false, precision = 22, scale = 0)
	public double getMeter() {
		return meter;
	}

	public void setMeter(double meter) {
		this.meter = meter;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other)
			return true;
		if (other == null)
			return false;
		if (!(other instanceof CheckpointId))
			return false;
		CheckpointId castOther = (CheckpointId) other;

		return getIdActivitie() == castOther.getIdActivitie() && getMeter() == castOther.getMeter();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + getIdActivitie();
		result = 37 * result + (int) getMeter();
		return result;
	}

}
