package com.run2gether.backend.model;
// Generated 24-may-2016 23:17:21 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CheckpointId generated by hbm2java
 */
@Embeddable
public class CheckpointId implements java.io.Serializable {

	private static final long serialVersionUID = 4L;
	private int idActivity;
	private double meter;

	public CheckpointId() {
	}

	public CheckpointId(int idActivity, double meter) {
		this.idActivity = idActivity;
		this.meter = meter;
	}

	@Column(name = "id_activity", nullable = false)
	public int getIdActivity() {
		return idActivity;
	}

	public void setIdActivity(int idActivity) {
		this.idActivity = idActivity;
	}

	@Column(name = "meter", nullable = false, precision = 22, scale = 0)
	public double getMeter() {
		return meter;
	}

	public void setMeter(double meter) {
		this.meter = meter;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other)
			return true;
		if (other == null)
			return false;
		if (!(other instanceof CheckpointId))
			return false;
		CheckpointId castOther = (CheckpointId) other;

		return getIdActivity() == castOther.getIdActivity() & getMeter() == castOther.getMeter();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + getIdActivity();
		result = 37 * result + (int) getMeter();
		return result;
	}

}
