package com.run2gether.backend.model;
// Generated 16-may-2016 18:34:41 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendId generated by hbm2java
 */
@Embeddable
public class FriendId implements java.io.Serializable {

	private static final long serialVersionUID = 5L;
	private int idUser;
	private String idFriend;

	public FriendId() {
	}

	public FriendId(int idUser, String idFriend) {
		this.idUser = idUser;
		this.idFriend = idFriend;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "idFriend", nullable = false, length = 45)
	public String getIdFriend() {
		return idFriend;
	}

	public void setIdFriend(String idFriend) {
		this.idFriend = idFriend;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other)
			return true;
		if (other == null)
			return false;
		if (!(other instanceof FriendId))
			return false;
		FriendId castOther = (FriendId) other;

		return getIdUser() == castOther.getIdUser()
				&& (getIdFriend() == castOther.getIdFriend() || getIdFriend() != null && castOther.getIdFriend() != null
						&& getIdFriend().equals(castOther.getIdFriend()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + getIdUser();
		result = 37 * result + (getIdFriend() == null ? 0 : getIdFriend().hashCode());
		return result;
	}

}
