package com.run2gether.backend.model;
// Generated 16-may-2016 18:34:41 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Friend generated by hbm2java
 */
@Entity
@Table(name = "friend", catalog = "run2gether_dev")
public class Friend implements java.io.Serializable {

	private static final long serialVersionUID = 4L;
	private FriendId id;
	private String status;

	public Friend() {
	}

	public Friend(FriendId id) {
		this.id = id;
	}

	public Friend(FriendId id, String status) {
		this.id = id;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idUser", column = @Column(name = "idUser", nullable = false)),
			@AttributeOverride(name = "idFriend", column = @Column(name = "idFriend", nullable = false, length = 45)) })
	public FriendId getId() {
		return id;
	}

	public void setId(FriendId id) {
		this.id = id;
	}

	@Column(name = "status", length = 9)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
