package com.run2gether.backend.model;
// Generated 24-may-2016 23:17:21 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendId generated by hbm2java
 */
@Embeddable
public class FriendId implements java.io.Serializable {

	private static final long serialVersionUID = 6L;
	private int idUser;
	private int idFriend;

	public FriendId() {
	}

	public FriendId(int idUser, int idFriend) {
		this.idUser = idUser;
		this.idFriend = idFriend;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_friend", nullable = false)
	public int getIdFriend() {
		return idFriend;
	}

	public void setIdFriend(int idFriend) {
		this.idFriend = idFriend;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other)
			return true;
		if (other == null)
			return false;
		if (!(other instanceof FriendId))
			return false;
		FriendId castOther = (FriendId) other;

		return getIdUser() == castOther.getIdUser() && getIdFriend() == castOther.getIdFriend();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + getIdUser();
		result = 37 * result + getIdFriend();
		return result;
	}

}
