package com.run2gether.backend.model;
// Generated 08-may-2016 18:26:46 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupactivities generated by hbm2java
 */
@Entity
@Table(name = "groupactivities", catalog = "run2gether_dev")
public class Groupactivities implements java.io.Serializable {

	private static final long serialVersionUID = 2L;
	private int idGroupActivities;
	private Users users;
	private String startDate;
	private String resume;
	private Set<Usersgroupactivities> usersgroupactivitieses = new HashSet<Usersgroupactivities>(0);

	public Groupactivities() {
	}

	public Groupactivities(int idGroupActivities, Users users) {
		this.idGroupActivities = idGroupActivities;
		this.users = users;
	}

	public Groupactivities(int idGroupActivities, Users users, String startDate, String resume,
			Set<Usersgroupactivities> usersgroupactivitieses) {
		this.idGroupActivities = idGroupActivities;
		this.users = users;
		this.startDate = startDate;
		this.resume = resume;
		this.usersgroupactivitieses = usersgroupactivitieses;
	}

	@Id

	@Column(name = "idGroupActivities", unique = true, nullable = false)
	public int getIdGroupActivities() {
		return idGroupActivities;
	}

	public void setIdGroupActivities(int idGroupActivities) {
		this.idGroupActivities = idGroupActivities;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAdmin", nullable = false)
	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "StartDate", length = 45)
	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "Resume")
	public String getResume() {
		return resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupactivities")
	public Set<Usersgroupactivities> getUsersgroupactivitieses() {
		return usersgroupactivitieses;
	}

	public void setUsersgroupactivitieses(Set<Usersgroupactivities> usersgroupactivitieses) {
		this.usersgroupactivitieses = usersgroupactivitieses;
	}

}
