package com.run2gether.backend.model;
// Generated 07-may-2016 22:23:29 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Logro generated by hbm2java
 */
@Entity
@Table(name = "logros", catalog = "run2gether_dev")
public class Logro implements java.io.Serializable {

	private static final long serialVersionUID = 3L;
	private int id;
	private String descripcion;
	private String icon;
	private Set<Userslogros> userslogroses = new HashSet<Userslogros>(0);

	public Logro() {
	}

	public Logro(int id) {
		this.id = id;
	}

	public Logro(int id, String descripcion, String icon, Set<Userslogros> userslogroses) {
		this.id = id;
		this.descripcion = descripcion;
		this.icon = icon;
		this.userslogroses = userslogroses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "icon", length = 45)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logros")
	public Set<Userslogros> getUserslogroses() {
		return this.userslogroses;
	}

	public void setUserslogroses(Set<Userslogros> userslogroses) {
		this.userslogroses = userslogroses;
	}

}
