package com.run2gether.backend.model;
// Generated 07-may-2016 22:23:29 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersgroupactivitiesId generated by hbm2java
 */
@Embeddable
public class UsersgroupactivitiesId implements java.io.Serializable {

	private static final long serialVersionUID = 6L;
	private int idGroupActivities;
	private int idUser;

	public UsersgroupactivitiesId() {
	}

	public UsersgroupactivitiesId(int idGroupActivities, int idUser) {
		this.idGroupActivities = idGroupActivities;
		this.idUser = idUser;
	}

	@Column(name = "idGroupActivities", nullable = false)
	public int getIdGroupActivities() {
		return this.idGroupActivities;
	}

	public void setIdGroupActivities(int idGroupActivities) {
		this.idGroupActivities = idGroupActivities;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersgroupactivitiesId))
			return false;
		UsersgroupactivitiesId castOther = (UsersgroupactivitiesId) other;

		return (this.getIdGroupActivities() == castOther.getIdGroupActivities())
				&& (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdGroupActivities();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
