package com.run2gether.backend.model;
// Generated 07-may-2016 22:23:29 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usersgroupactivities generated by hbm2java
 */
@Entity
@Table(name = "usersgroupactivities", catalog = "run2gether_dev")
public class Usersgroupactivities implements java.io.Serializable {

	private static final long serialVersionUID = 5L;
	private UsersgroupactivitiesId id;
	private Groupactivity groupactivity;
	private User user;
	private String date;

	public Usersgroupactivities() {
	}

	public Usersgroupactivities(UsersgroupactivitiesId id, Groupactivity groupactivity, User user, String date) {
		this.id = id;
		this.groupactivity = groupactivity;
		this.user = user;
		this.date = date;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idGroupActivities", column = @Column(name = "idGroupActivities", nullable = false)),
			@AttributeOverride(name = "idUser", column = @Column(name = "idUser", nullable = false)) })
	public UsersgroupactivitiesId getId() {
		return this.id;
	}

	public void setId(UsersgroupactivitiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGroupActivities", nullable = false, insertable = false, updatable = false)
	public Groupactivity getGroupactivities() {
		return this.groupactivity;
	}

	public void setGroupactivities(Groupactivity groupactivity) {
		this.groupactivity = groupactivity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser", nullable = false, insertable = false, updatable = false)
	public User getUsers() {
		return this.user;
	}

	public void setUsers(User user) {
		this.user = user;
	}

	@Column(name = "date", nullable = false, length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
