package com.run2gether.backend.model;
// Generated 21-may-2016 10:44:53 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usergroupactivity generated by hbm2java
 */
@Entity
@Table(name = "usergroupactivity", catalog = "run2gether_dev")
public class Usergroupactivity implements java.io.Serializable {

	private static final long serialVersionUID = 11L;
	private UsergroupactivityId id;
	private Groupactivitiy groupactivitiy;
	private User user;
	private Date date;
	private Date dateModified;

	public Usergroupactivity() {
	}

	public Usergroupactivity(UsergroupactivityId id, Groupactivitiy groupactivitiy, User user, Date date) {
		this.id = id;
		this.groupactivitiy = groupactivitiy;
		this.user = user;
		this.date = date;
	}

	public Usergroupactivity(UsergroupactivityId id, Groupactivitiy groupactivitiy, User user, Date date,
			Date dateModified) {
		this.id = id;
		this.groupactivitiy = groupactivitiy;
		this.user = user;
		this.date = date;
		this.dateModified = dateModified;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idGroupactivities", column = @Column(name = "id_groupactivities", nullable = false)),
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)) })
	public UsergroupactivityId getId() {
		return id;
	}

	public void setId(UsergroupactivityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_groupactivities", nullable = false, insertable = false, updatable = false)
	public Groupactivitiy getGroupactivitiy() {
		return groupactivitiy;
	}

	public void setGroupactivitiy(Groupactivitiy groupactivitiy) {
		this.groupactivitiy = groupactivitiy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", length = 19)
	public Date getDateModified() {
		return dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
