package com.run2gether.backend.model;
// Generated 24-may-2016 23:17:21 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsergroupactivityId generated by hbm2java
 */
@Embeddable
public class UsergroupactivityId implements java.io.Serializable {

	private static final long serialVersionUID = 12L;
	private int idGroupactivities;
	private int idUser;

	public UsergroupactivityId() {
	}

	public UsergroupactivityId(int idGroupactivities, int idUser) {
		this.idGroupactivities = idGroupactivities;
		this.idUser = idUser;
	}

	@Column(name = "id_groupactivities", nullable = false)
	public int getIdGroupactivities() {
		return idGroupactivities;
	}

	public void setIdGroupactivities(int idGroupactivities) {
		this.idGroupactivities = idGroupactivities;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other)
			return true;
		if (other == null)
			return false;
		if (!(other instanceof UsergroupactivityId))
			return false;
		UsergroupactivityId castOther = (UsergroupactivityId) other;

		return getIdGroupactivities() == castOther.getIdGroupactivities() && getIdUser() == castOther.getIdUser();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + getIdGroupactivities();
		result = 37 * result + getIdUser();
		return result;
	}

}
