package com.run2gether.backend.model;
// Generated 21-may-2016 10:44:53 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserachievementId generated by hbm2java
 */
@Embeddable
public class UserachievementId implements java.io.Serializable {

	private static final long serialVersionUID = 10L;
	private int idAchievement;
	private int idUser;

	public UserachievementId() {
	}

	public UserachievementId(int idAchievement, int idUser) {
		this.idAchievement = idAchievement;
		this.idUser = idUser;
	}

	@Column(name = "id_achievement", nullable = false)
	public int getIdAchievement() {
		return idAchievement;
	}

	public void setIdAchievement(int idAchievement) {
		this.idAchievement = idAchievement;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other)
			return true;
		if (other == null)
			return false;
		if (!(other instanceof UserachievementId))
			return false;
		UserachievementId castOther = (UserachievementId) other;

		return getIdAchievement() == castOther.getIdAchievement() && getIdUser() == castOther.getIdUser();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + getIdAchievement();
		result = 37 * result + getIdUser();
		return result;
	}

}
